test:
  AWS_ACCESS_KEY_ID: AKIAJRZYJLIOF2RUF3PA
  AWS_SECRET_ACCESS_KEY: 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
  AWS_ASSOCIATE_TAG: gopiggybank-20
  CACHE: false
  LOCALE: us
  ENCODING: iso-8859-15

development:
  AWS_ACCESS_KEY_ID: AKIAJRZYJLIOF2RUF3PA
  AWS_SECRET_ACCESS_KEY: 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
  AWS_ASSOCIATE_TAG: gopiggybank-20
  CACHE: false
  LOCALE: us
  ENCODING: iso-8859-15

staging:
  AWS_ACCESS_KEY_ID: AKIAJRZYJLIOF2RUF3PA
  AWS_SECRET_ACCESS_KEY: 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
  AWS_ASSOCIATE_TAG: gopiggybank-20
  CACHE: false
  LOCALE: us
  ENCODING: iso-8859-15

production:
  AWS_ACCESS_KEY_ID: AKIAJRZYJLIOF2RUF3PA
  AWS_SECRET_ACCESS_KEY: 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
  AWS_ASSOCIATE_TAG: gopiggybank-20
  CACHE: false
  LOCALE: us
  ENCODING: iso-8859-15